name: Docker Image CI

on:
  push:
    branches: master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          VERSION: ${{ matrix.version }}
        run: |
          export TAG_VERSION=${{ matrix.version }}
          docker build . --file ${{ matrix.version }}/slim/Dockerfile --tag chinayin/node:${TAG_VERSION}
          docker build . --file ${{ matrix.version }}/pm2/Dockerfile --tag chinayin/node:${TAG_VERSION}-pm2
          docker build . --file ${{ matrix.version }}/nuxt/Dockerfile --tag chinayin/node:${TAG_VERSION}-nuxt
          docker image ls

      - name: Push image to Docker hub
        if: success()
        env:
          VERSION: ${{ matrix.version }}
        run: |
          export TAG_VERSION=${{ matrix.version }}
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/node:${TAG_VERSION}
          docker push chinayin/node:${TAG_VERSION}-pm2
          docker push chinayin/node:${TAG_VERSION}-nuxt
          docker logout

#      - name: Push image to Aliyun Container Registry
#        if: success()
#        env:
#          VERSION: ${{ matrix.version }}
#        run: |
#          export TAG_VERSION=${{ matrix.version }}
#          echo ${{ secrets.ALIYUN_CR_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_CR_USER }} registry.cn-beijing.aliyuncs.com --password-stdin
#          docker tag chinayin/node:${TAG_VERSION} registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}
#          docker tag chinayin/node:${TAG_VERSION}-pm2 registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}-pm2
#          docker tag chinayin/node:${TAG_VERSION}-nuxt registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}-nuxt
#          docker push registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}
#          docker push registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}-pm2
#          docker push registry.cn-beijing.aliyuncs.com/chinayin/node:${TAG_VERSION}-nuxt
#          docker logout
