name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 12,14 ]
        os: [ buster-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep ' NODE_VERSION ' Dockerfile | awk '{print $3}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
  build-slim:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        major: [ 12,14 ]
        os: [ slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep ' NODE_VERSION ' Dockerfile | awk '{print $3}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.os }}
  build-pm2:
    runs-on: ubuntu-latest
    needs: build-slim
    strategy:
      matrix:
        major: [ 12,14 ]
        os: [ pm2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep ' NODE_VERSION ' Dockerfile | awk '{print $3}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.os }}
